### ISSUE TITLE
Add quiet option for disabling logging to stderr

### ISSUE THREAD

**Issue by ammannbe** [abbbi/virtnbdbackup#137]
Other linux commands do provide a `--quiet` option or separate stdout and stderr.
For example I backup my virtual machine disks every day through cronjob and send an email with the result.
But if possible I don't want to send all the output generated, but only errors.

Is that possible? Thanks!

**Comment by abbbi** [comment]
Hi, thanks for the Feedback! Yes, i think that option would be possible by removing the logging module stderr handler if its passed

**Comment by abbbi** [comment]
just pushed changes with new option to master, likes or sponsoring welcome if you like the project
thanks

**Comment by ammannbe** [comment]
Thank you very much for the implementation and sorry for the late reply!
I just tested the changes: is it also possible to disable only the stdout (but keep stderr) output?

**Comment by abbbi** [comment]
>  is it also possible to disable only the stdout (but keep stderr) output?

no plans to do so currently. If exit code != 0 then something went wrong; its possible to check the logs then. Otherwise --strict can be used, so warnings will change exit code aswell.
