### ISSUE TITLE
Incremental size way bigger than expected after fstrim

### ISSUE THREAD

**Issue by Zoltan-LS** [abbbi/virtnbdbackup#138]
**Version used**
0.99

**Describe the bug**
I am unsure if it is a normal behavior or if this is specific to kvm. The problem that I am seeing is that the incremental backups become 2-3 times the size of the disk  after fstrim is executed. 

-rw-r--r-- 1 root root  13G Oct  3 01:12 sda.full.data
-rw-r--r-- 1 root root 168M Oct  3 05:15 sda.inc.virtnbdbackup.1.data
-rw-r--r-- 1 root root 131M Oct  3 09:15 sda.inc.virtnbdbackup.2.data
-rw-r--r-- 1 root root  75M Oct  3 13:15 sda.inc.virtnbdbackup.3.data
-rw-r--r-- 1 root root  72M Oct  3 17:15 sda.inc.virtnbdbackup.4.data
-rw-r--r-- 1 root root  72M Oct  3 21:15 sda.inc.virtnbdbackup.5.data
-rw-r--r-- 1 root root  38G Oct  4 01:21 sda.inc.virtnbdbackup.6.data
-rw-r--r-- 1 root root 174M Oct  4 05:21 sda.inc.virtnbdbackup.7.data

**Expected behavior**
I'd expect/like to see this smaller in size. Is there any work around for this? 

**Hypervisor information:**
 - OS: Alma
 - HV type plain libvirt 

**Logfiles:**
Dont see any relevant logs to provide.

**Workaround:**
Work around is to execute the fstrim before the full backup

**Comment by Zoltan-LS** [comment]
Fair enough. I thought that may be the case here, it was just a slight hope that maybe you encountered this and found a fix for such cases.

**Comment by abbbi** [comment]
I dont have a Solution (Other than timing fstrim with full backups) ..

**Comment by abbbi** [comment]
other solutions bassd on dirty bitmaps have the same „Issue“:

https://forum.proxmox.com/threads/huge-dirty-bitmap-after-sunday.110233/

So id say it works as designed. Maybe running fstrim on the host makes more Sense.
