### ISSUE TITLE
Standard output python logging errors - KeyError: 'light_blue'

### ISSUE THREAD

**Issue by de666** [abbbi/virtnbdbackup#148]
**Version used**
1.9.48

**Describe the bug**
Lot of python logging errors on standard output when running backup from docker image, all similar to this
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 430, in format
    return self._format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 426, in _format
    return self._fmt % record.__dict__
KeyError: 'light_blue'
``` 

and all ending with
```
KeyError: 'light_blue'
``` 

**Expected behavior**
No errors

**Hypervisor information:**
 - OS: Ubuntu Server 22.04
 - HV type libvirt

**Logfiles:**
Backup logs are ok, it seems it's an issue related to the standard output

**Comment by abbbi** [comment]
Strange, Erich Version of the colorlog Module do you have installed? How die you install virtnbdbackup? The issue is within the log output color module Not virtnbdbackup itself.

**Comment by draggeta** [comment]
I'm having the sdame problem. I'm using the docker container and it reports this as well:
```
ValueError: Formatting field not found in record: 'light_blue'   
```

**Comment by abbbi** [comment]
which docker container? I dont maintain any official docker images for virtnbdbackup, only the scripts to create the container by yourself. Might well be that the docker container used is using incompatible versions of the python modules.

Official debian and other rpm based distributions ship python3-colorlog which has the light_blue color defined:

```
grep light_blue /usr/lib/python3/dist-packages/colorlog/escape_codes.py
    "light_blue": 94,
    "light_blue": 104,
dpkg -S /usr/lib/python3/dist-packages/colorlog/escape_codes.py
python3-colorlog: /usr/lib/python3/dist-packages/colorlog/escape_codes.py
```

**Comment by draggeta** [comment]
I wasn't clear enough. I use the dockerfile in this repository indeed to build the container. It seems that it uses an old version:

```
/# apt list python3-colorlog
Listing... Done
python3-colorlog/now 4.7.2-1 all [installed,local] 
```

**Comment by abbbi** [comment]
Thanks,  i rarely use the docker images. There Bades on devian bullseye. Ill change the dockerfile to use bookworm

**Comment by abbbi** [comment]
all components now set a strict dependency to python3-colorlog >= 6.4.1

**Comment by abbbi** [comment]
@adrianparilli you might want to consider updating your docker images aswell

**Comment by abbbi** [comment]
hmm.. i reconsidered. Im using the color code regular "blue" now which is available in all colorlog verisons. Its bad to lose compatiblity with older debian and rhel distributions just for a slight color change.

**Comment by draggeta** [comment]
Thank you for the quick fix by the way 👍
