### ISSUE TITLE
Incremental backup fails with error "ImportError: cannot import name 'sighandle'" after previous successful full backup

### ISSUE THREAD

**Issue by ThomasFrickB** [abbbi/virtnbdbackup#157]
**Version used**
Version 2.0 as is in RPM package 'virtnbdbackup-2.0-1.noarch.rhel8.rpm'

**Describe the bug**
After having created full backups of all running libvirt-guests without any errors, the following incremental backups failed in total with this error message for each guest: File "/bin/virtnbdbackup", line 27, in `<module>`
    from libvirtnbdbackup import sighandle
ImportError: cannot import name 'sighandle'.

**Expected behavior**
I expected getting incremental backups for all guests and no errors.

**Hypervisor information:**
 - OS: Alma release 8.9 (Midnight Oncilla)
 - HV is plain libvirt/QEMU

**Logfiles:**
No log files found on system, but I can give you the reported traceback:
"Traceback (most recent call last):
  File "/bin/virtnbdbackup", line 27, in `<module>`
    from libvirtnbdbackup import sighandle
ImportError: cannot import name 'sighandle'"

**Workaround:**
Have no idea, sorry.

**Comment by abbbi** [comment]
this looks like a broken installation to me.
How did you install?

**Comment by abbbi** [comment]
ive just installed the package on a fresh alma 8.8 instance and the required sighandle.py is included in the package. I wonder how this fails for you because signal handling code is loaded no matter if full or incremental backup is attempted. 

```
[root@alma8-cli t]# rpm -ql virtnbdbackup | grep sighandle\.py
/usr/lib/python3.6/site-packages/libvirtnbdbackup/sighandle.py
```
