### ISSUE TITLE
After first offline backup the second fail with "does not contain full backup"

### ISSUE THREAD

**Issue by slu-010101** [abbbi/virtnbdbackup#161]
**Version used**
virtnbdbackup --version
2.0

**Describe the bug**
Can't execute switch to auto incremental backup: specified target folder [/mnt/snapshot/2024_12/winABCDEF] does not contain full backup.

**Expected behavior**
If the vm is offline during the first auto backup, the second backup should do nothing because there was no change.
Or if it impossible to detect changes backup the complete disk again.

**Hypervisor information:**
Debian 12.5
libvirt-daemon 9.0.0-4

**Logfiles:**
Please attach generated logfiles relevant to the reported issue.
[virtnbdbackup.log](https://github.com/abbbi/virtnbdbackup/files/14648639/virtnbdbackup.log)
[virtnbdbackup_fail.log](https://github.com/abbbi/virtnbdbackup/files/14648640/virtnbdbackup_fail.log)

**Comment by abbbi** [comment]
An Offline backup cannot be used as full backup because if virtual machine is offline no Checkpoint can be created using libvirt api.

To actually be able to create a full backup, virtual machine must be online.

**Comment by slu-010101** [comment]
But in this case should never start a backup with auto?
And is the first backup healthy, even if the machine was offline?

**Comment by abbbi** [comment]
> But in this case should never start a backup with auto? And is the first backup healthy, even if the machine was offline?

1) if virtual machine is offline and backup mode is "auto" it fails back to backup mode "copy"
2) if virtual machine is online and backup mode is "auto" and target directory is empty it creates an full backup

its possible to workaround this with pre scripts, check if VM is online if you want a full backup to be created

**Comment by abbbi** [comment]
See this issue for progress on that topic:

https://github.com/abbbi/virtnbdbackup/issues/164
