### ISSUE TITLE
amount of backup data in human readable size (MB/GB/TB)

### ISSUE THREAD

**Issue by abbbi** [abbbi/virtnbdbackup#173]
### Discussed in https://github.com/abbbi/virtnbdbackup/discussions/172

<div type='discussions-op-text'>

<sup>Originally posted by **slu-010101** April  7, 2024</sup>
Hi,

it would be nice to make this info more human readable:

> [2024-04-07 12:50:09] INFO root disk - backup [vda]:  Got 7183 extents to backup.
> [2024-04-07 12:50:09] INFO root disk - backup [vda]:  2147483648000 bytes disk size
> [2024-04-07 12:50:09] INFO root disk - backup [vda]:  1351024640 bytes of data extents to backup

Or some statistic after the successful backup to see something is curious (ransomware,...).
</div>

**Comment by slu-010101** [comment]
Thank you very much, this project is awesome!

**Comment by tuomotalvitie** [comment]
I'm not absolutely sure if this is the reason for my error, but these two lines do not seem to enjoy working together:
https://github.com/abbbi/virtnbdbackup/blob/af8fb448c7480203e5d4cba25e4463a5fae634ee/libvirtnbdbackup/backup/disk.py#L182
https://github.com/abbbi/virtnbdbackup/blob/af8fb448c7480203e5d4cba25e4463a5fae634ee/libvirtnbdbackup/backup/disk.py#L219

> ERROR root virtnbdbackup - main [main]:  unsupported operand type(s) for +: 'int' and 'dict'

> File "/usr/local/lib/python3.10/dist-packages/virtnbdbackup-2.8-py3.10.egg/libvirtnbdbackup/backup/disk.py", line 219, in backup
    backupSize = sum(blen for blen in compressedSizes)
