### ISSUE TITLE
Fedora 39 - RHEL9 - ModuleNotFoundError: No module named 'nbd'

### ISSUE THREAD

**Issue by WardPearce** [abbbi/virtnbdbackup#174]
Running `virtnbdbackup` on Fedora 39 results in the following for me.

```python
Traceback (most recent call last):
  File "/usr/bin/virtnbdbackup", line 27, in <module>
    from nbd import __version__ as __nbdversion__
ModuleNotFoundError: No module named 'nbd'
```

I install virtnbdbackup via `virtnbdbackup-2.7-1.noarch.rhel9.rpm`

Running `sudo dnf install python3-libnbd` results in my system telling me `Package python3-libnbd-1.18.3-1.fc39.x86_64 is already installed`

**Comment by abbbi** [comment]
please check which python version is used.

head -1 /usr/bin/virtnbdbackup

packages are not tested for fedora.
Probably python version is pulled by environment that is not the one for which nbd module is available.

**Comment by abbbi** [comment]
i just attempted to test this within docker container (fedora:latest).
The packages are built for RHEL9 which seems to use python 3.9:

```
[root@e645b6d84763 /]# head -1 /usr/bin/virtnbdbackup 
#!/usr/bin/python3.9
```

but the python3-libnbd package is only built for python 3.12:

```
[root@e645b6d84763 /]# rpm -ql python3-libnbd
/usr/bin/nbdsh
/usr/lib/.build-id
/usr/lib/.build-id/b0
/usr/lib/.build-id/b0/0134dac0bbfaa40839472790ed2d0bb403d9e1
/usr/lib64/python3.12/site-packages/__pycache__/nbd.cpython-312.opt-1.pyc
/usr/lib64/python3.12/site-packages/__pycache__/nbd.cpython-312.pyc
/usr/lib64/python3.12/site-packages/__pycache__/nbdsh.cpython-312.opt-1.pyc
/usr/lib64/python3.12/site-packages/__pycache__/nbdsh.cpython-312.pyc
/usr/lib64/python3.12/site-packages/libnbdmod.cpython-312-x86_64-linux-gnu.so
/usr/lib64/python3.12/site-packages/nbd.py
/usr/lib64/python3.12/site-packages/nbdsh.py
/usr/share/man/man1/nbdsh.1.gz
```

which seems to be the default python version.
Thus the nbd module is not found..
One way would be to adjust the shebang in the executable to workaround.

**Comment by WardPearce** [comment]
Yea ran `sed -i 's|#!/usr/bin/python3.9|#!/usr/bin/python3.12|' /usr/bin/virtnbdbackup` to change the shebang. 

Now for some reason it can't find the local module `libvirtnbdbackup`

**Comment by abbbi** [comment]
i need to prepare a seperate package compatible to fedora 3.9
or you attempt to use a python pyenv as alternative.

**Comment by WardPearce** [comment]
Yea I tried using virtualenv, but had build errors.

**Comment by abbbi** [comment]
please try with the packages included in the arifact from this build:

https://github.com/abbbi/virtnbdbackup/actions/runs/8601118081

the attached artifact includes packages compatible to fedora 39 (.noarch.fedora9.rpm)
I was able to successfully install and run them within a fedora39 container.

**Comment by WardPearce** [comment]
Yup `virtnbdbackup-2.7-1.noarch.fedora39.rpm` worked as expected.

**Comment by abbbi** [comment]
next release will build packages for fedora 39 too.

**Comment by cbol848** [comment]
Hi, I'm on Fedora 41 with Python 3.13. I get the same error. I've installed the Fedora49.rpm package
