### ISSUE TITLE
Plausibility check for backup (amount of data)

### ISSUE THREAD

**Issue by slu-010101** [abbbi/virtnbdbackup#175]
Hi,

not sure this is an interesting enhancement for virtnbdbackup because this is much more than "only" backup.

My idea is some plausibility checks for backups, for example the amount of data during backup is approximately 120 - 130 GB per incremental backup. If it's more or less then something is wrong, in the worst case ransomware produce more data during encryption for example.

Just an idea...

**Comment by abbbi** [comment]
hi,

sorry, this is beyond the skope of what i want to implement. After all i need to care about all the features.
Its easy to script around this, by using post/pre scripts you execute before and after backup.
