### ISSUE TITLE
backup with compression enabled fails: unsupported operand type(s) for +: 'int' and 'dict'

### ISSUE THREAD

**Issue by abbbi** [abbbi/virtnbdbackup#177]
I'm not absolutely sure if this is the reason for my error, but these two lines do not seem to enjoy working together:
https://github.com/abbbi/virtnbdbackup/blob/af8fb448c7480203e5d4cba25e4463a5fae634ee/libvirtnbdbackup/backup/disk.py#L182
https://github.com/abbbi/virtnbdbackup/blob/af8fb448c7480203e5d4cba25e4463a5fae634ee/libvirtnbdbackup/backup/disk.py#L219

> ERROR root virtnbdbackup - main [main]:  unsupported operand type(s) for +: 'int' and 'dict'

> File "/usr/local/lib/python3.10/dist-packages/virtnbdbackup-2.8-py3.10.egg/libvirtnbdbackup/backup/disk.py", line 219, in backup
    backupSize = sum(blen for blen in compressedSizes)

_Originally posted by @tuomotalvitie in https://github.com/abbbi/virtnbdbackup/issues/173#issuecomment-2075044612_

**Comment by abbbi** [comment]
@tuomotalvitie  .. i can reproduce this :(

**Comment by abbbi** [comment]
fixed in 2.9

**Comment by tuomotalvitie** [comment]
Thank you, that was extremely fast, and worked quite nicely :) 

As a side note tags/v2.7 worked as well, as can be expected (but in case someone wanders here and wonders). (Originally I was going to go with the .deb, but Ubuntu wanted to install some strange packages, so I decided this was probably better option).

**Comment by abbbi** [comment]
> Thank you, that was extremely fast, and worked quite nicely :)
> 
> As a side note tags/v2.7 worked as well, as can be expected (but in case someone wanders here and wonders). (Originally I was going to go with the .deb, but Ubuntu wanted to install some strange packages, so I decided this was probably better option).

the issue only happens with compressed backups if there are blocks processed from the NBD server which exceed
the maximum block size. They are then split into 32 MB parts and if this happens, the list of compressed blocks also
includes a dict where usually an int would be...

Depends on the size of the disk and changed block regions to be progressed. My automatic tests didnt catch it because the regions were not as big. I was able to reproduce with bigger disks/regions.
