### ISSUE TITLE
Debug option --printonly make backup in auto mode

### ISSUE THREAD

**Issue by sikorapatryk** [abbbi/virtnbdbackup#189]
**Version used**
2.10

**Describe the bug**
Invoking a command:
`virtnbdbackup --printonly -d vm01 -l auto -o /backup/vm01/$(date +"%Y/%U") --scratchdir /backup/vm01 -i vda --freeze-mountpoint / --noprogress --compress --nocolor`
when the target folder `-o /backup/vm01/$(date +"%Y/%U")` is empty causes the full backup to be started.

**Expected behavior**
Information about the size of the full backup or a warning that there is no backup in the target location yet should be displayed.

**Hypervisor information:**
 - OS: Red Hat Enterprise Linux 9.3 (Plow)
 - HV type: libvirt-10.0.0-6.3.el9_4.x86_64 qemu-kvm-8.0.0-16.el9_3.3.x86_64

**Comment by abbbi** [comment]
--printonly can only work if there is already an checkpoint existant, to estimate the backup size of an incremental or differencial backup. The check involves if there is an parent checkpoint:

`if args.printonly and args.cpt.parent and not args.offline:`

args.cpt.parent doesnt exist in this case thus its executing an backup.
