### ISSUE TITLE
ubuntu 20.X compatibility

### ISSUE THREAD

**Issue by insatomcat** [abbbi/virtnbdbackup#19]
Hello,

In the documentation it is said about the qemu/libvirt requirement:
"Debian bullseye or Ubuntu 20.x include libvirt versions supporting this feature already."

It made me think virtnbdbackup was natively compatible with Ubuntu 20.4 (LTS).

However on the libnbd requirement it said : 
"python libnbd bindings (https://github.com/libguestfs/libnbd) version >= 1.5.5 (yum install python3-libnbd)"

Ubuntu 20.X comes with libnbd 1.2.2:

```
$ apt search python3-libnbd
Sorting... Done
Full Text Search... Done
python3-libnbd/focal 1.2.2-1ubuntu2 amd64
  Network Block Device client library -- Python 3 bindings
```

And indeed, I couldnt make virtnbdbackup work with libnbd 1.2.2...

Am I right in saying that to make virtnbdbackup work on Ubuntu 20.X, it is needed to add a custom version of libnbd ?

Thanks

**Comment by abbbi** [comment]
Maybe consider using docker to run virtnbdbackup, or use a custom built version, theres no other way:

https://github.com/adrianparilli/virtnbdbackup-docker
