### ISSUE TITLE
[2024-09-22 18:33:51] ERROR root job - start [main]:  Failed to start backup: [internal error: unable to execute QEMU command 'transaction': Bitmap already exists: virtnbdbackup.0]

### ISSUE THREAD

**Issue by linuxgokan** [abbbi/virtnbdbackup#219]
Hello

How can I fix this problem? I moved the systems, and when I tried to reinstall it, it gave me this error.

virtnbdbackup -V
2.15

**Comment by linuxgokan** [comment]
thanks for the information. Is it a problem if I delete the checkpoint directly like below without copying the virtual disk to NAS?

Disk status:

qemu-img info vm1.qcow2
image: vm1.qcow2
file format: qcow2
virtual size: 400 GiB (429496729600 bytes)
disk size: 640 GiB
cluster_size: 65536
Snapshot list:
ID    	TAG           	VM SIZE            	DATE 	VM CLOCK 	ICOUNT
1     	0hali             	0 B 2023-03-04 15:24:39 00:00:00.000      	 
Format specific information:
	compat: 1.1
	compression type: zlib
	lazy refcounts: true
	bitmaps:
    	[0]:
        	flags:
            	[0]: auto
        	name: virtnbdbackup.0
        	granularity: 65536
	refcount bits: 16
	corrupt: false
	extended l2: false

-% bitmap remove
qemu-img bitmap --remove vm1.qcow2 virtnbdbackup.0

**Comment by abbbi** [comment]
No

**Comment by linuxgokan** [comment]
very thanks. I was able to get a replacement.
