### ISSUE TITLE
Installation issue on v0.29 requirements.txt missing.

### ISSUE THREAD

**Issue by SeeJayEmm** [abbbi/virtnbdbackup#22]
Unable to install v0.29 from the tarball.
'''
# python3 setup.py install
Traceback (most recent call last):
  File "/tmp/virtnbdbackup-0.29/setup.py", line 23, in <module>
    install_requires=open("requirements.txt").read().splitlines(),
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
'''

I tried searching the repo for requirements.txt and couldn't find the actual file.

**Comment by abbbi** [comment]
meh, seems its not added to the tarball with dist...

**Comment by abbbi** [comment]
Use the regular git tarball, it shold be included in it:

https://github.com/abbbi/virtnbdbackup/archive/refs/tags/v0.29.tar.gz

**Comment by abbbi** [comment]
Fixed with new release.
