### ISSUE TITLE
backup schedualing feature

### ISSUE THREAD

**Issue by aminhashemi1994** [abbbi/virtnbdbackup#233]
Hi,

its been a while since we are using your backup as our main backup service for our virtualization (qemu/kvm) services. 
i have developed a wrapper in bash that use your virtnbdbackup script and tries to create schedualed backup from our vms.
its working fine, but the schedualer i have developed is not very advanced and creates a weekly and monthly backup.
but the main problem is that creating an advanced schedualer in bash is not very simple and i was wondering if you have any plan on adding a schedualer feature for creating backup in the near future.

**Comment by abbbi** [comment]
I dont intend to do do, schedulers have been implemented and solutions exist, no need to re invent .. use cron or alike to schedule this utility
