### ISSUE TITLE
Fedora 41: ModuleNotFoundError: No module named 'nbd'

### ISSUE THREAD

**Issue by cbol848** [abbbi/virtnbdbackup#234]
Hi, 
I have exactly the same problem as described here: #174 but now with Fedora 41...

I've installed the virtnbdbackup fedora39.rpm package from release page, latest release.

I think I have python 3.13 installed. python3-libnbd from distro repository is installed as well.

**Comment by abbbi** [comment]
fedora 39 packages are not compatible to fedora41.

ive just added package build for fedora 41 and the installation test passes.
Please try the packages contained in the following build artifact:

https://github.com/abbbi/virtnbdbackup/actions/runs/11824342435/artifacts/2183950018

**Comment by cbol848** [comment]
Thank you for the quick response. With fedora41 rpm it now works!
