### ISSUE TITLE
Backup behavior with different VM power states

### ISSUE THREAD

**Issue by steeldomejeff** [abbbi/virtnbdbackup#236]
**Version used**
2.17

**Describe the bug**
Question rather than bug declaration.

When I attempt to backup a new VM which is powered off I notice the backup completes fine the first time, but does not create a checkpoint file. Then if I attempt to run the backup again, I receive an error as shown below in the log entries. Is this expected behavior?

If I backup a new VM that powered on, the initial backups and all successive backup complete without error. The checkpoint file is in place upon the first backup.

**Hypervisor information:**
 - OS: Rocky 9.4
 - HV type KVM 9.1

**Log entries:**

INFO Backup level: [auto]
INFO Libvirt library version: [10008000]
INFO NBD library version: [1.20.3]
INFO Backup will save [1] attached disks.
INFO Concurrent backup processes: [1]
ERROR No existing checkpoints found, execute full backup first.

**Comment by abbbi** [comment]
https://github.com/abbbi/virtnbdbackup?tab=readme-ov-file#backing-up-offline-virtual-domains
