### ISSUE TITLE
Incremental backup chain broken after Alma Linux 9 OS update in the VM

### ISSUE THREAD

**Issue by asitemade4u** [abbbi/virtnbdbackup#237]
**Version used**
**2.17**

**Describe the bug**
- I created a backup chain on an Alma Linux 9.4 VM: first a full backup then incremental ones. All worked perfectly.
- The VMs I am using were all converted to `qcow3` format.
- Then there was a kernel update on Alma Linux 9.5 (`5.14.0-503.14.1.el9_5.x86_64`) and the backup chain now fails with this error message : 

```log
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root job - start [main]:  Starting backup job.[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m fs fs - freeze [main]:  Freezed [2] filesystems.[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m fs fs - thaw [main]:  Thawed [2] filesystems.[0m
[32m[2024-11-24 05:59:54][0m[34m [31mERROR[0m root job - start [main]: [31m Failed to start backup: [checkpoint inconsistent: missing or broken bitmap 'virtnbdbackup.22' for disk 'vda'][0m
```

**Expected behavior**
One would expect that a relatively minor OS update in the VM would not break down the incremental backup chain.
Instead, that virtnbdbackup would be able to cope with minor changes at the OS level.

**Hypervisor information:**
 - OS: AlmaLinux 9.5
 - HV type: cockpit-machines with `libvirt-10.5.0-7.el9_5.alma.1.src.rpm`installed

**Logfiles:**
```log
[32m[2024-11-24 05:59:54][0m[34m INFO[0m lib common - printVersion [main]:  Version: 2.17 Arguments: /usr/local/bin/virtnbdbackup -d al9cdr -l inc -o /zfs212/vms-bkp/al9cdr[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root virtnbdbackup - main [main]:  Backup level: [inc][0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root virtnbdbackup - main [main]:  Libvirt library version: [10005000][0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root virtnbdbackup - main [main]:  NBD library version: [1.20.2][0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root disktype - Optical [main]:  Skipping attached [cdrom] device: [sda].[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root virtnbdbackup - main [main]:  Backup will save [1] attached disks.[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root virtnbdbackup - main [main]:  Concurrent backup processes: [1][0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root checkpoint - create [main]:  Loading checkpoints from: [/zfs212/vms-bkp/al9cdr/al9cdr.cpt][0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root checkpoint - redefine [main]:  Loading checkpoint list from: [/zfs212/vms-bkp/al9cdr/checkpoints][0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root checkpoint - create [main]:  Checkpoint handling.[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root checkpoint - create [main]:  Next checkpoint id: [23].[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root checkpoint - create [main]:  Parent checkpoint name [virtnbdbackup.22].[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root checkpoint - create [main]:  Using checkpoint name: [virtnbdbackup.23].[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root virtnbdbackup - main [main]:  Local NBD Endpoint socket: [/var/tmp/virtnbdbackup.142995][0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root virtnbdbackup - main [main]:  Temporary scratch file target directory: [/var/tmp][0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m root job - start [main]:  Starting backup job.[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m fs fs - freeze [main]:  Freezed [2] filesystems.[0m
[32m[2024-11-24 05:59:54][0m[34m INFO[0m fs fs - thaw [main]:  Thawed [2] filesystems.[0m
```

**Workaround:**
1. delete the backup folder
2. remove all virtual image checkpoints one by one
3. recreate the full backup
4. check an incremental backu
5. = 10 mn work for 10 machines = an hour and a half of avoidable chores!

**Comment by abbbi** [comment]
I dont see how virtnbdbackup is at fault here, did the alma update lose libvirt checkpoint information?

**Comment by abbbi** [comment]
The checkpoints are not the bitmaps, the bitmaps for a checkpoint are saved in the qcow images directly

in your case the checkpoints are existing bit the bitmaps are missing

**Comment by abbbi** [comment]
In a situation where the checkpoints exist but the bitmaps are missing there is something seriously wrong, I could remove the checkpoints forcefully in this case ( during full backup ) but diring incorrect diff backups there is no way to recover gracefully and continue the backup chain

**Comment by abbbi** [comment]
> > in your case the checkpoints are existing bit the bitmaps are missing
> 
> How would that even happen?? The backup destination is a ZFS pool, and as such super-secure.

Something must have altered the qcow images

**Comment by abbbi** [comment]
> > Something must have altered the qcow images
> 
> I can emphatically tell you that is NOT the case. Except, of course, for the OS update I performed on them.

The Backup util does not touch the qcow images for the bitmaps in any way it all goes through the libvirt api.

If libvirt is removing a checkpoint it also deletes the bitmap. This usually only happens during a full backup.

**Comment by abbbi** [comment]
Like said, you should check what has reset bitmap information in the qcow images, check with qemu-img info util if they are all gone or just some of them.

**Comment by abbbi** [comment]
Yes that’s the reason for the issue
How that can Happen: I don’t know
