### ISSUE TITLE
Raw units can only be backed up in full

### ISSUE THREAD

**Issue by inode64** [abbbi/virtnbdbackup#239]
When you try to backup a virtual machine with a raw disk if an incremental, differential or auto backup has been configured and a previous backup already exists and then you perform an incremental backup
that displays an error indicating that only a full backup can be performed

**Version used**
2.17

**Expected behavior**
show an error indicating the need to only use a full backup with raw drives

**Hypervisor information:**
kvm

**Comment by abbbi** [comment]
can you show an example log? Based on the idea of the implementation if raw devices are included, it should create a full backup.

**Comment by abbbi** [comment]
so i have a VM with one raw device and one regular, i do:

./virtnbdbackup -d vm4 -o /tmp/foo --raw -l full

this will backup both devices.

Now if i create inc backup:
```

[2024-11-28 16:59:31] WARNING root virtnbdbackup - main [main]:  Raw disks can't be included during incremental or differential backup.
[2024-11-28 16:59:31] WARNING root virtnbdbackup - main [main]:  Excluding raw disks.
```

**Comment by abbbi** [comment]
https://github.com/abbbi/virtnbdbackup/commit/dd6aa2fc4d0b31e7a852529acd29ffe64bacad13

**Comment by inode64** [comment]
the command I use

/usr/bin/virtnbdbackup -d win2k12r2 --nocolor --noprogress -q --raw --compress -l auto -o /mnt/backup/kvm/win2k12r2/2024-46

If I am using auto, the first backup is done correctly and in that virtual machine there is a raw drive

I have already seen in commit. I see it well,
unless a backup is made of the units that are not raw and thus avoid the error
