### ISSUE TITLE
README errors

### ISSUE THREAD

**Issue by volman36** [abbbi/virtnbdbackup#26]
1) There is a typo in [Backup fails with "Failed to bind socket to /var/tmp/virtnbdbackup.XX: Permission denied"](https://github.com/abbbi/virtnbdbackup#backup-fails-with-failed-to-bind-socket-to-vartmpvirtnbdbackupxx-permission-denied):

```
/var/tmp/virtnbdbackup.* rw
/var/tmp/backup.* rw,
```
should be a comma (,) at the end of first line:
```
/var/tmp/virtnbdbackup.* rw,
/var/tmp/backup.* rw,
```

2) In [Installation of Debian package](https://github.com/abbbi/virtnbdbackup#debian-package):

In a standard Debian 11 (Bullseye) installation one more package is missing that is required: `python3-lz4`

Should be:
```
sudo apt-get install python3-all python3-stdeb dh-python python3-libnbd python3-tqdm python3-lz4
python3 setup.py --command-packages=stdeb.command bdist_deb
```

**Comment by abbbi** [comment]
fixed, thanks!

**Comment by volman36** [comment]
Thanks for fixing. And thank you for a great tool!
