### ISSUE TITLE
Cannot get it running on alma 8.6

### ISSUE THREAD

**Issue by madmax01** [abbbi/virtnbdbackup#49]
**when i try to install rpm i get this error:**

dnf install -y virtnbdbackup-0.66-1.noarch.rpm
Last metadata expiration check: 3:49:33 ago on Fri 01 Jul 2022 11:08:14 BST.
Error:
 Problem: conflicting requests
  - nothing provides nbdkit-plugin-python3 needed by virtnbdbackup-0.66-1.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**i don't find such an "nbdkit-plugin-python3"**

----------------------------------

./virtnbdbackup
Traceback (most recent call last):
  File "./virtnbdbackup", line 34, in <module>
    from libvirtnbdbackup import extenthandler
  File "/root/virtnbdbackup-0.66/libvirtnbdbackup/extenthandler/__init__.py", line 21, in <module>
    from .extenthandler import ExtentHandler
  File "/root/virtnbdbackup-0.66/libvirtnbdbackup/extenthandler/extenthandler.py", line 18, in <module>
    from nbd import CONTEXT_BASE_ALLOCATION
ImportError: cannot import name 'CONTEXT_BASE_ALLOCATION'

seems there are dependencies missing not part of the requirements.txt

**Comment by abbbi** [comment]
The NBD module is not shipped via pypi, as such i cant add it to requirements.txt
You have installed the "nbd" module from pypi which unfortunately has the same python module name but does not provide the same functionality, thus you get the CONTEXT_BASE_ALLOCATION error.

See issues #43 and #44

**Comment by abbbi** [comment]
Dependencies are fixed in master branch. It also appears as if bdist_rpm requires the --python parameter on almalinux, otherwise bdist_rpm strange enough picks /bin/python3 as requirement, which is not provided by any package.

**Comment by madmax01** [comment]
Hello @abbbi 

many thx for fast Response ;). looking forward to test the program.

i can confirm i was able to install now without issues.

many thx for assistance. ;)
