### ISSUE TITLE
Dockerfile - python3-lxml

### ISSUE THREAD

**Issue by jadegouws** [abbbi/virtnbdbackup#55]
HI Abbbi

Thanks so much for a great project and it's something we are busy testing and may roll it out to all production servers.

When building the Dockerfile on Ubuntu22.04, I had to add the python3-lxml package to the Dockerfile to get it to run

JG

**Comment by jadegouws** [comment]
Thank you! 💯

**Comment by abbbi** [comment]
> Thank you! 100

@jadegouws i would welcome some feedback, in regard of how many virtual machines you backup and data sizes, aswell if everything is working out for you guys, or features that would be good. Actively looking for some Feedback :)

**Comment by jadegouws** [comment]
Will do, we are still in the early days, what is the best way to communicate?

**Comment by abbbi** [comment]
> Will do, we are still in the early days, what is the best way to communicate?

maybe via https://github.com/abbbi/virtnbdbackup/discussions
