### ISSUE TITLE
How to automatically create daily backups?

### ISSUE THREAD

**Issue by Hoeze** [abbbi/virtnbdbackup#6]
Hi, we would like to perform daily backups with virtnbdbackup.
Therefore, we want to always keep one full backup and two snapshots, e.g.:
```
2021-04-09.img -> full backup
2021-04-10.img -> snapshot
2021-04-11.img -> snapshot
<currently running state>
```

How would I configure this with virtnbdbackup?
Also, how do we restore a backup?

**Comment by abbbi** [comment]
virtnbdbackup does not use snapshotting for backup, no snaphots are created. It uses changed block tracking.
If you wan to rotate every two days, switch the output folder

day 1 (full backup)

virtnbdbackup -l full .. -o cycle1

day 2 (incremental)

virtndbackup  -l inc -o cycle1

day 3 (incremental) 

virtnbdbackup -l inc -o cycle1

mv cycle1 2021-04-backup1

-> start over.
For restore, please see readme.

**Comment by Hoeze** [comment]
Thanks for the detailed answer @abbbi :slightly_smiling_face:
