### ISSUE TITLE
Version 0.75-1  invalid choice: 'auto'

### ISSUE THREAD

**Issue by madmax01** [abbbi/virtnbdbackup#62]
Hello,

when trying to use "auto"  for the backup level i get an Error. i downloaded latest Source.

usage: virtnbdbackup [-h] -d DOMAIN [-l {copy,full,inc,diff}]
                     [-t {stream,raw}] [-r] -o OUTPUT [-C CHECKPOINTDIR]
                     [-S SCRATCHDIR] [-i INCLUDE] [-x EXCLUDE] [-f SOCKETFILE]
                     [-n] [-z] [-w WORKER] [-e] [-q] [-s] [-k] [-p] [-v]
virtnbdbackup: error: argument -l/--level: invalid choice: 'auto' (choose from 'copy', 'full', 'inc', 'diff')

thx

Max

**Comment by abbbi** [comment]
it seems you execute an old version which is somewhere in your $PATH
latest version includes auto function for sure. Please check your environment (which virtnbdbackup)

**Comment by madmax01** [comment]
hm very strange.... all i done is installed the rpm's last versions.... and then done upgrade to new version with dnf.....

i removed it again and checked > seems found old versions in the bin path,......deleted them out (not sure why was left,.. may a bug from older versions)

i reinstalled the latest rpm's > but now i get other error

 /usr/bin/virtnbdbackup
 
Traceback (most recent call last):
  File "/usr/bin/virtnbdbackup", line 39, in <module>
    from libvirtnbdbackup.logcount import logCount
ModuleNotFoundError: No module named 'libvirtnbdbackup.logcount'
------------

/usr/lib/python3.6/site-packages/libvirtnbdbackup/      i see logcount.py there.

if i execute the virtnbdbackup inside the Source Folder it works.....may the rpm-build didn't integrated everything,.... sounds like variable Issue or so ?

thx

**Comment by abbbi** [comment]
> /usr/bin/virtnbdbackup
> 
> Traceback (most recent call last): File "/usr/bin/virtnbdbackup", line 39, in from libvirtnbdbackup.logcount import logCount ModuleNotFoundError: No module named 'libvirtnbdbackup.logcount'
> 
> /usr/lib/python3.6/site-packages/libvirtnbdbackup/ i see logcount.py there.
> 
> if i execute the virtnbdbackup inside the Source Folder it works.....may the rpm-build didn't integrated everything,.... sounds like variable Issue or so ?
> 
> thx

you probably built the new rpm package you updated to with a different python version, so now
include paths are not correct. (python3.9 vs python3.6) issue. Check which python is used by 

head /usr/bin/virtnbdbackup

and which include path is used for module.

**Comment by madmax01** [comment]
ah seems something was broken with python... not exact sure....... i reinstalled everything  and now works.

thx ;)
