### ISSUE TITLE
When Backup process getting interrupted - State not getting cleared

### ISSUE THREAD

**Issue by madmax01** [abbbi/virtnbdbackup#63]
Hello,

i recognized when backup process is interrupted (fault or manually)     (Crash can always happening,.....shouldn't > but can)

1:   **Backup recognize there is no Full Backup > but it tries Inc with Auto flag**

[2022-07-13 09:51:10] INFO virtnbdbackup - main [MainThread]: Backup level: [auto]
[2022-07-13 09:51:10] INFO virtnbdbackup - main [MainThread]: Compression enabled
[2022-07-13 09:51:10] ERROR virtnbdbackup - main [MainThread]: Cant execute switch to auto incremental backup: target folder seems not to include full backup.

files inside the set

-rw-r--r-- 1 root     root      498 Jul 13 09:49 backup.auto.07132022094916.log
-rw-r--r-- 1 root     root      498 Jul 13 09:51 backup.auto.07132022095110.log
-rw-r--r-- 1 root     root     2.6K Jul 13 09:29 backup.full.07132022092955.log
drwxr-xr-x 2 root     root        6 Jul 13 09:29 checkpoints

checkpoints are empty.

2:   **when this happens also for an new Backup try Error is: libvirt.libvirtError: internal error: unable to execute QEMU command 'transaction': Bitmap already exists: virtnbdbackup.0**

maybe fix possible ?

1: possible to flip back to Full in this Case to avoid Inc getting tried when Full is not there?
2: possible to clear an wrong Bitmap or so when Backup was faulty?

**Comment by madmax01** [comment]
just manually i cleared out the folder and removed the bitmap  with qemu-img bitmap --remove   (not sure what's difference between --remove and --clear)

just in Case this is interesting to be fixed automatically by the Tool (once backup process is interrupted)

thinking this is just the Case when "init" Backup fails..... when Inc backup fails > seems still works after when re/trying

**Comment by abbbi** [comment]
Situation depends how full backup failed or was cancelled..logfile required at what step the application failed or was cancelled.

**Comment by abbbi** [comment]
close -> 14 days w/o additional info.
