### ISSUE TITLE
Restoring a single disk into Folder which is not empty give an Error

### ISSUE THREAD

**Issue by madmax01** [abbbi/virtnbdbackup#64]
Hi,

when restore a single disk into vm folder where other files are already there its blaming... i had to move it temp somewhere else and manually move it to the folder.

ERROR virtnbdrestore - main [MainThread]: Target directory is not empty.

is there an way to say "force" so the disk is getting restored equal if folder empty or not

**Comment by abbbi** [comment]
no, restore must happen to empty directory because now overwrite function is implemented (that would mean to trim blocks within already existing qcow image) so this works like designed at the moment.
