### ISSUE TITLE
Compile error since v0.80

### ISSUE THREAD

**Issue by skleijkers** [abbbi/virtnbdbackup#68]
Hi,

I've used virtnbdbackup for some while now and didn't upgrade from the 0.59 version till now. I'm trying to upgrade to the latest release but I'm getting a compile error. I've traced back till the 0.79 version, that's the last version with a correct compile. From the 0.80 onwards all compiles fail with the same error. I've attached the output of the 0.80 compile. Am I missing something or do I hit a bug?

Stefan
[output.txt](https://github.com/abbbi/virtnbdbackup/files/9379789/output.txt)

**Comment by abbbi** [comment]
you miss the python3-paramiko package on the system. Need to add this to the build-depends, though.
Should work after installing python3-paramiko

**Comment by abbbi** [comment]
Fixed in latest release, now adds python3-paramiko to build dependencies and build should stop before compile error noticing user about missing build-deps.
