### ISSUE TITLE
Running full Backup from Crontab -> no backup created

### ISSUE THREAD

**Issue by x8n1620** [abbbi/virtnbdbackup#73]
**Version used**
1.3

**Describe the bug**
When I run my backupscript manually, virtnbdbackup -l auto or -l full creates a full backup, when the target folder ist empty
When I run the script via crontab, no backup will be created
When the folder contains a (manually created) Full-backup, my script creates incremental backups, also started via crontab.

I have also echo the generated command from the script to a log file:
   virtnbdbackup -d Server1 -l auto -nzo /mnt//Backupdir/VMs/snapshot.00/Server1
When I copy&paste it to a command line, the full-backup works as expected. 
When I paste the command directly to the crontab, without any Variables, also no fullbackup is created.

**Expected behavior**
Creating a full backup, when the folder is empty (-l auto), no matter if started via crontab or manually

**Hypervisor information:**
 - OS: Rocky Linux release 9.0 (Blue Onyx)
 - HV type: libvirt

**Comment by abbbi** [comment]
is a logfile created in the target directory? i think this might be caused by TQDM /progressbar, can you check for a created logfile and try with --noprogress option, if possible?

**Comment by x8n1620** [comment]
There is no logfile generated in the Target Directory. 
I have set the -n option.

**Comment by abbbi** [comment]
if no logfile is created, it fails before everything else is executed. Have you received any mail to the user executing the crontab? II guess this is an environment issue then, if utility is executed via crontab.

**Comment by x8n1620** [comment]
I got no mail.  virtnbdbackup runs under the root account.
When a Full-Backup exist, the Incremental-Backups run also via crontab. I can't believe, that this is a environment issue.

**Comment by abbbi** [comment]
i just tried to reproduce with following crontab entry:

`* * * * * /home/abi/virtnbdbackup/virtnbdbackup -d vm1 -l auto -o /tmp/BACKUP `

the utility gets executed every minute and i at least have a logfile for each execution in the target directory.

**Comment by abbbi** [comment]
hm.. this is pretty strange. Im executing the utility as regular user, and it in fact is executed by the cronjob. According to debug info it is using qemu:///session as login session. Using virsh i can see the virtual domain running:
```

virsh -c qemu:///session list
 Id   Name   State
----------------------
 3    vm1    running
```

but during execution, virtnbdbackup thinks the virtual machine is offline and attempts to create an offline backup:

```
INFO virtnbdbackup - main [MainThread]: qemu:///session
virtnbdbackup - startOfflineNBD [sda]: Offline backup, starting NDB Service
```

which then fails bcs the vm is of course online and the disk file is locked:

`[2022-09-25 22:52:01] ERROR virtnbdbackup - main [MainThread]: Unable to backup Disk: [Unable to start [qemu-nbd] error: [qemu-nbd: Failed to blk_new_open '/tmp/tmp.SBs8E1Vno8/vm1-sda.qcow2': Failed to get shared "write" lock`

as if libvirts python bindings for domObj.isActive() returns something else if executed via cron? very strange.

**Comment by abbbi** [comment]
its an issue with the uri parameter defaulting to qemu:///session if executed via cron.
executing virsh via cron gives:

```
* * * * * virsh list --all > /tmp/virsh
cat /tmp/virsh 
 Id   Name   State
-----------------------
 -    vm1    shut off
```

so apparrently if exeucted via cron, the session ends up with another context. not sure about the background here.

executing virtnbdbackup with:

`-U qemu:///system`

will probably fix your issue.

**Comment by x8n1620** [comment]
Try -U qemu:///system, still no luck.
When the issue is gone, when I run my backup as non-root user, I can create a dedicated backup user (tomorrow).

**Comment by abbbi** [comment]
i guess it depends with which user context the virtual machine was actually defined, was this virtual machine defined with the root user or another regular system user?

**Comment by x8n1620** [comment]
The VMs was all defined as root

**Comment by abbbi** [comment]
Like said, i cant reproduce this behavior on my system, everything is working like expected if the virtual machines i want to backup have been defined by the same user im executing the cronjob with. In *evey* case virtnbdbackup allways attempts to create an logfile before it does any operation. If even no logfile is created in your case, is suspect something to go really wrong on your system.

In any case if cron is setup correctly, it at least sends an e-mail upon execution with all output lines from the executed utility, if even not that is happening on your system, i fail to see how this would be an bug in virtnbdbackup.

**Comment by x8n1620** [comment]
oops
tail -f /tmp/log 
/mnt/daten/Sicherung/Sicherungsscripts/backup_work2.bin.sh: line 20: virtnbdbackup: command not found

**Comment by x8n1620** [comment]
When I give the full path to virtnbdbackup or set the PATH Variables in my script, the Full-Backup is running. Thanks for your hints to find this rookie mistake.

My Backup is running at this moment, this will take time.
But I've no Idea, why my incremental backup is running in the past, even starting from a cron job.
