### ISSUE TITLE
Fail backup when the name of the disk has no extension 

### ISSUE THREAD

**Issue by inode64** [abbbi/virtnbdbackup#81]
**Version used**
1.9

**Describe the bug**
If you create a virtual machine and the disk does not have a .qcow2 extension, it shows the following error

**Expected behavior**
A correct backup
Thanks

**Hypervisor information:**
 - OS: Gentoo 
 - HV  libvirt version 8.0

**Logfiles:**
[2022-11-11 01:01:57] INFO common - printVersion [MainThread]: Version: 1.9 Arguments: /usr/lib/python-exec/python3.10/virtnbdbackup -S /tmp/ -d VRobotOfitec --noprogress -q --compress -l auto -o /srv/backup/VRobotOfitec/2022-45
[2022-11-11 01:01:57] INFO virtnbdbackup - main [MainThread]: Backup level: [auto]
[2022-11-11 01:01:57] INFO virtnbdbackup - main [MainThread]: Compression enabled, level [2]
[2022-11-11 01:01:57] INFO virtnbdbackup - main [MainThread]: Backup mode auto, target folder is empty: executing full backup.
[2022-11-11 01:01:57] INFO virtnbdbackup - main [MainThread]: Libvirt library version: [8008000]
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/virtnbdbackup", line 992, in <module>
    main()
  File "/usr/lib/python-exec/python3.10/virtnbdbackup", line 518, in main
    disks = virtClient.getDomainDisks(args, vmConfig) or (
  File "/usr/lib/python3.10/site-packages/libvirtnbdbackup/libvirthelper/libvirthelper.py", line 380, in getDomainDisks
    diskFileName = os.path.basename(diskSrc)
  File "/usr/lib/python3.10/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by inode64** [comment]
This is the xml format, it creates with cockpit-machines 277

    <disk type='volume' device='disk'>                                                                                                                                                                             
      <driver name='qemu' type='qcow2' cache='writeback'/>                                                                                                                                                         
      <source pool='default' volume='VRobotOfitec'/>                                                                                                                                                               
      <target dev='vda' bus='virtio'/>                                                                                                                                                                             
      <serial>VRobotOfitec.qcow2</serial>                                                                                                                                                                          
      <boot order='1'/>                                                                                                                                                                                            
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>                                                                                                                                  
    </disk>

**Comment by abbbi** [comment]
the issue is probably not the missing extension (its in serial) but the format the virtual machine has the disk attached. Its using hte source pool definition style. Bugfix would probably be

1) get the pool information of the source pool: location where the pool is located
2) get the path to the complete disk image file by source pool location and "serial" setting..

**Comment by inode64** [comment]
That's what I thought, but I don't know why cockpit creates the disks in this way

**Comment by abbbi** [comment]
> That's what I thought, but I don't know why cockpit creates the disks in this way

well, i think it is somewhat the "right". livirt has the concept of pools and volumes, its just not used everywhere and most
configurations just point to a direct file.  Need to check the libvirt api what would be the best way, maybe it also works
by getting the volume information, it might return the path to the disk, too.

**Comment by abbbi** [comment]
```
>>> import libvirt
>>> con = libvirt.open()
>>> con.storagePoolLookupByName('default')
<libvirt.virStoragePool object at 0x7fb3c25dbc10>
>>> pool = con.storagePoolLookupByName('default')
>>> vol = pool.storageVolLookupByName('generic-VAGRANTSLASH-alma8_vagrant_box_image_4.0.2_box.img')
>>> vol.path()
'/var/lib/libvirt/images/generic-VAGRANTSLASH-alma8_vagrant_box_image_4.0.2_box.img'
```

**Comment by inode64** [comment]
Anything you need, tell me, I'll try to help
At the moment I have changed to disk type='file' to be able to continue making backups

**Comment by abbbi** [comment]
hi, check version from dev branch, includes commit 

https://github.com/abbbi/virtnbdbackup/commit/85c1ca624b5a1040b1df977fa1c222cfe79c10a5

which should fix this issue.
