### ISSUE TITLE
Feature to backup xmls of guest networks configs

### ISSUE THREAD

**Issue by damiankaczkowski** [abbbi/virtnbdbackup#96]
Hi. Please consider enhancing virtnbdbackup with feature to backup xmls of networks configs used by guest alongside "vmconfig.copy.xml". I am talking about configs in "/etc/libvirt/qemu/networks". They can be listed by "virsh net-list" and dumped by "virsh net-dumpxml". Networks configs are required to restore guest to different location/hypervisor. For more advanced networks it is a must to have a backup of those configs. Good starting point would be to just allow virtnbdbackup to backup a copy of networks xmls used by guest. Reinstalling networks configs during recovery would be nice but not required. Greets.

**Comment by abbbi** [comment]
why not backup these files with a regular file backup solution like restic etc?

**Comment by damiankaczkowski** [comment]
Seems reasonable. But I still have a feeling that I miss something. You just can't restore (i a sense of reachability) machine with multiple interfaces and tagged vlans without this information. You need at least vlan info to at least know where you should connect which interface. Otherwise quest will not be reachable. Without this info in xmls, you will have to login to machine to check its configuration, which will be troublesome, moreover in case a guests that needs SSO and working network to login, this will be even more troublesome.

Also there is an inconsistency. For example, you can have a vlan information inside guest xml. But you can leverage just "portgoup" (openvsiwtch) element instead of direct vlan config which holds vlan information in network xml file. So in one case when you backup you store vlan info in other case you do not. It should be failry easy to just query network backend for source network then query portgroup and then export only that part of xml so we can just have necessary guest config for future usage.

I think such network config is more a guest config not libvirt config in general. Not sure about other backends.

**Comment by abbbi** [comment]
like said, implementing this is currently not in my use scope, you could introduce a script in your backup workflow that dumps specific network config xml via virsh.

Im happy to merge a pull request that enhances virtnbdbackup, given the fact that it comes with proper test cases in the testsuite so its assured things dont break in the future.

**Comment by damiankaczkowski** [comment]
Understood. Thank you for your time and advice. I am not able to provide a patch so I will close that. Greets.
