### ISSUE TITLE
Should "Domain is offline" message be tagged at WARNING level?

### ISSUE THREAD

**Issue by damiankaczkowski** [abbbi/virtnbdbackup#99]
If you backup offline domains using "--level auto" (which should handle offline domains just fine as part of auto backup workflow) you get a WARNING in log files. Is this ok? I mean after backup I review logs for errors , warnings, and such. Backup went ok. There are no ERRORs, however there is one WARNING for every offline guest. If this would be INFO or other level then logs would be free from ERRORs and WARNINGs. Please consider if it is ok to change this message level to something less severe. Greets.

`backup.auto.01162023160235.log:[2023-01-16 16:02:35] WARNING root virtnbdbackup - setOfflineArguments [MainThread]: Domain is offline, resetting backup options.`

**Comment by abbbi** [comment]
during level auto, if you expect the virtual machine is online, and you want to create incremental backup, backup will fallback to differential backup, so i think this warning justified, otherwise you would wonder why there was an differential backup executed instead of the expected incremental backup.

**Comment by damiankaczkowski** [comment]
Hmmm... I do not expect guest to be online. In auto I except tool to be as smart as possible and just make working backup regardless of machine state ; ). But thanks for explanation, maybe it is valid for some workflows. Feel free to close this if you consider it is ok now. Thank you for your time.

**Comment by abbbi** [comment]
If the backup application changes the backup mode from incremental to differential because of environmental changes, i would expect that it notifies me, and if the change has effect on stored backup size, i think this justifies an warning.
